theme: jekyll-theme-cayman
repository_name: brepo
title: brepo
emoji: 🏗️
description:
  A base template repository to quickly bootstrap new projects with
  preconfigured structure, essential files, and common workflows.
show_downloads: true
collections:
  pages:
    output: true # Generates HTML files for each file
    permalink: /:path/ # URL structure for collection items
